create extension if not exists pgcrypto;

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  no integer not null unique,
  code text not null unique,
  project_name text not null,
  company text not null,
  rep_email text not null,
  phone_last4 text not null check (phone_last4 ~ '^[0-9]{4}$'),
  folder_url text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.access_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text not null,
  phone_last4 text not null check (phone_last4 ~ '^[0-9]{4}$'),
  success boolean not null,
  team_no integer,
  code text,
  company text,
  user_agent text,
  ip_hash text
);

create index if not exists teams_lookup_idx
  on public.teams (lower(rep_email), phone_last4)
  where active = true;

create index if not exists access_logs_code_created_at_idx
  on public.access_logs (code, created_at desc);

create index if not exists access_logs_email_created_at_idx
  on public.access_logs (lower(email), created_at desc);

alter table public.teams enable row level security;
alter table public.access_logs enable row level security;

drop policy if exists "No public read access to teams" on public.teams;
drop policy if exists "No public read access to access logs" on public.access_logs;

create policy "Service role can manage teams"
  on public.teams
  for all
  to service_role
  using (true)
  with check (true);

create policy "Service role can manage access logs"
  on public.access_logs
  for all
  to service_role
  using (true)
  with check (true);
